apiVersion: v1
kind: Service
metadata:
  name: fluentd-injector
  namespace: kube-system
  labels:
    app: fluentd-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: fluentd-injector